name: Release

on:
  push:
    branches:
      - main
<<<<<<< HEAD
      - devel
      - qa
  pull_request:
    branches:
      - main
      - devel
      - qa
=======
>>>>>>> 1fa4a6f6cad32a88d9ecdda5c9eb7de468234fb3

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - run: npm install
      - run: npm test

  releases:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - run: npm install

      - name: Release new version NPM
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
