name: Release

on:
  push:
    branches:
      - main
      - devel
      - qa
  pull_request:
    branches:
      - main
      - devel
      - qa

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - run: npm install
      - run: npm test

  releases:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - run: npm install
      - run: npm test
      - run: npm build
      - name: Release new version NPM
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm semantic-release
